//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whould you like to get another rates for *{0}*?.
        /// </summary>
        public static string AnotherRates {
            get {
                return ResourceManager.GetString("AnotherRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code dictionary.
        /// </summary>
        public static string CurrencyDictionary {
            get {
                return ResourceManager.GetString("CurrencyDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I encountered an error.
        ///Please, try again later..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the currency literal code
        ///(_e.g._ *USD*. _If you are not familiar with it, use the link below_):.
        /// </summary>
        public static string InputCurrencyCode {
            get {
                return ResourceManager.GetString("InputCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the date to get currency rates for
        ///(_the date should be not earlier than 01.12.2014 and in format:_ *dd.MM.yy*):.
        /// </summary>
        public static string InputDate {
            get {
                return ResourceManager.GetString("InputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Invalid date!*
        ///
        ///.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not find the exchange rate for *{0}* on *{1}*..
        /// </summary>
        public static string NotFoundRate {
            get {
                return ResourceManager.GetString("NotFoundRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Privatbank:*
        ///    Purchase: {0}
        ///    Sale: {1}
        ///*NBU:*
        ///    Purchase: {2}
        ///    Sale: {3}.
        /// </summary>
        public static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The *{0}/{1}* exchange rates on *{2}*:
        ///
        ///.
        /// </summary>
        public static string RateStringBase {
            get {
                return ResourceManager.GetString("RateStringBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Currency Bot* welcomes you!
        ///
        ///.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
